#!/usr/bin/env sage-python
"""
Compute Adams differentials d2-d5 of the EHP spectral sequence from the
lambda algebra E2 data (with C2 map data), and write chart CSVs (spheres
plus the n=0 C2 column) for pages E2-E5.

Run from this directory with:  sage -python run.py [tot] [--data DIR]

Only tridegrees with s+f <= tot and n <= 2*tot are loaded; deductions beyond
those bounds would rest on incomplete data. Outputs are written relative to
the current directory, so run from python/.

Inputs:
  --data DIR - E2 page data generated by the rust lambda algebra code
               (default: data/E2):
               E2_{rank,relations,E,H,P,C2}.csv (+ optional E2_names.json).
               If a precomputed d2 differential file  <DIR>/d2  is present it
               is loaded (so the run starts the page turn at E3); otherwise
               d2 is computed and saved there for the next run
  stable/   - known differentials: stable_sphere_diffs.csv applies to every
              sphere in the stable range (n > s+1), c2_diffs.csv to the n=0
              column (both resolved by check_stable() during compute());
              Unstable{r}.txt hand lists are imposed before compute() on E3/E4

d2 is loaded from <DIR>/d2 (or computed once if absent); d3, d4, d5 are always
recomputed from the E2 data and the page turns, then saved to data/E{r}/d{r}.

Outputs:
  data/E{r}/d{r}          - differential data with proof chains (JSON), plus
                            d{r}_unknown.csv with the tridegrees where d_r
                            remains undetermined (d3-d5; d2 lives in <DIR>/d2)
  charts/E{r}_{tot}.csv   - chart data for pages E2-E5 (includes the n=0 C2 column)
  data/E{r}/              - full page data for E3-E5
"""

import argparse
import os

from sage.all import GF, vector

from ehp_adams import SpectralSequence
from lib import Element

TOT = 70  # default total degree; the loader lowers it if the data covers less

def load_entry_list(path):
    """Parse a hand-written differential list into (n, s, f, row, col, value)
    tuples. Lines are `n s f row col value`; blank lines and `#` comments are
    ignored. Missing file -> empty list. Used for the optional Unstable{r}
    hand lists (hand-proved differentials layered on top of the stable
    inputs; see stable/README.md for the input-data conventions)."""
    entries = []
    if not os.path.exists(path):
        return entries
    with open(path) as fh:
        for lineno, line in enumerate(fh, 1):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            # A malformed line is a hand-editing accident; silently dropping
            # it would silently delete a hand-proved differential, so fail
            # loudly instead.
            if len(parts) != 6:
                raise ValueError(
                    f"{path}:{lineno}: malformed hand-list line "
                    f"(expected 6 whitespace-separated fields): {line!r}")
            try:
                entries.append(tuple(int(x) for x in parts))
            except ValueError as exc:
                raise ValueError(
                    f"{path}:{lineno}: non-integer field in hand-list "
                    f"line: {line!r}") from exc
    return entries


def _differential_state(page):
    """Comparable snapshot of a page's derived state: the dimension of the
    differential constraint space at every populated tridegree, plus the set
    of uncertain tridegrees. compute() only narrows spaces and resolves
    uncertainties, so two equal snapshots mean a fixpoint was reached."""
    dims = {}
    for tri, dim in page.dimension.items():
        if dim > 0:
            dims[tri] = page.d[tri].dimension()
    uncertain = page.uncertainty_manager.uncertain
    uncertain_keys = (
        sorted(uncertain.keys()) if hasattr(uncertain, "keys") else len(uncertain))
    return dims, uncertain_keys


MAX_EXTRA_CONVERGENCE_PASSES = 5


def compute_to_fixpoint(ss, verify):
    """ss.compute(), optionally re-run until the differential state stops
    changing. compute()'s own exit test ignores some progress signals (it can
    declare a fixpoint while later constraint passes would still shrink
    subspaces), so with `verify` this both detects and heals a premature
    exit; 0 extra passes = converged first try."""
    ss.compute()
    if not verify:
        return
    for extra in range(1, MAX_EXTRA_CONVERGENCE_PASSES + 1):
        before = _differential_state(ss.current_page)
        ss.compute()
        after = _differential_state(ss.current_page)
        if before == after:
            print(f"  convergence verified ({extra - 1} extra pass(es) needed)")
            return
        changed = sorted(
            set(k for k in after[0] if before[0].get(k) != after[0][k])
            | set(before[0]) - set(after[0]))
        print(f"  WARNING: compute() had not converged; extra pass {extra} "
              f"changed {len(changed)} tridegree(s), e.g. {changed[:8]}")
    raise RuntimeError(
        f"compute() still changing after {MAX_EXTRA_CONVERGENCE_PASSES} extra "
        f"passes; do not trust this state")


def stable_path(name):
    """Resolve a filename under the stable/ dir (run from python/), matching
    check_stable's convention."""
    return os.path.join("stable", name) if os.path.isdir("stable") else name


def main():
    parser = argparse.ArgumentParser(
        description="Compute Adams differentials d2-d5 of the EHP spectral sequence."
    )
    parser.add_argument(
        "tot", nargs="?", type=int, default=TOT,
        help=f"maximum total degree s+f to load (default: {TOT})",
    )
    parser.add_argument(
        "--data", default="data/E2", metavar="DIR",
        help="directory with the rust-generated E2 CSVs (default: data/E2)",
    )
    parser.add_argument(
        "--d2-file", default="d2", metavar="NAME",
        help="d2 filename under --data: loaded if it exists, otherwise computed "
             "fresh and saved there (default: d2)",
    )
    parser.add_argument(
        "--stop-after", type=int, default=5, metavar="R",
        help="highest page E_R to compute; pass 2 to stop right after d2 "
             "(default: 5)",
    )
    parser.add_argument(
        "--refine-d2", action="store_true",
        help="after loading a precomputed d2 file, run the constraint engine "
             "on top of it (stable/C2 tables, naturality, filtration-1 "
             "Leibniz) to resolve still-undetermined differentials, then save "
             "the refined d2 back. Without this flag a loaded d2 is used "
             "as-is and no d2 deduction happens at all",
    )
    parser.add_argument(
        "--fresh-d2", action="store_true",
        help="ignore any existing d2 cache and recompute d2 from scratch with "
             "the current inputs (stable/C2 lists), then save it. Use for a "
             "clean publication run after the inputs have changed.",
    )
    parser.add_argument(
        "--verify-converged", action="store_true",
        help="after each compute(), re-run it until the differential state "
             "stops changing and report how many extra passes were needed. "
             "Guards against a premature fixpoint exit in compute(); use "
             "for the definitive publication run.",
    )
    args = parser.parse_args()
    tot = args.tot

    print("=" * 80)
    print(f"LOADING E2 PAGE FROM {args.data} (tot={tot})")
    print("=" * 80)
    # The C2 map is detected from the presence of E2_C2.csv in the data dir.
    ss = SpectralSequence.from_data(args.data, r=2, tot=tot)

    d2_file = os.path.join(args.data, args.d2_file)
    if os.path.exists(d2_file) and args.fresh_d2:
        print(f"\n--fresh-d2: ignoring the existing d2 cache at {d2_file}; "
              f"recomputing from the current inputs.")
    if os.path.exists(d2_file) and not args.fresh_d2:
        print(f"\nLoading precomputed d2 from {d2_file}...")
        reshaped = ss.current_page.load_d(d2_file)
        if args.refine_d2:
            # Keep every deduction already in the file and continue from
            # there: check_stable re-applies the stable/C2 tables, then
            # naturality and the filtration-1 Leibniz rule narrow whatever
            # is still undetermined (e.g. C2-column d2s at bidegrees of
            # dimension >= 2, and their sphere consequences).
            print("Refining d2 on top of the loaded state...")
            compute_to_fixpoint(ss, args.verify_converged)
            if reshaped:
                # The cache covers a larger range than this session loaded;
                # saving over it would replace full-range entries with their
                # truncated projections. Keep the refinement in a side file.
                side_file = f"{d2_file}_tot{tot}"
                print(f"Cache covers a larger range than tot={tot}; saving "
                      f"refined d2 to {side_file} (original left untouched)")
                ss.current_page.save_d(side_file)
            else:
                ss.current_page.save_d(d2_file)
    else:
        # Compute d2 fresh: check_stable fills the stable/C2 differentials, the
        # filtration-1 Leibniz (h0-h3 maps) resolves the rest of the C2 column,
        # and naturality pulls that to the odd spheres. Saved for later runs.
        print(f"\nNo precomputed d2 at {d2_file}; computing d2...")
        compute_to_fixpoint(ss, args.verify_converged)
        ss.current_page.save_d(d2_file)
    ss.write_spheres()  # E2 chart

    for r in (3, 4, 5):
        if r > args.stop_after:
            break
        print("\n" + "=" * 80)
        print(f"TURNING PAGE TO E{r}")
        print("=" * 80)
        ss.next_page()  # induces maps (incl. C2), products, names; saves data/E{r}/

        # Unstable hand differentials (E3, E4 only): resolved by hand /
        # interpage in the UI, applied BEFORE compute so they propagate.
        if r in (3, 4):
            unstable = load_entry_list(stable_path(f"Unstable{r}.txt"))
            if unstable:
                print(f"\nApplying {len(unstable)} unstable hand d{r} "
                      f"differentials from Unstable{r}.txt...")
                imposed = ss.current_page.d.apply_entry_list(unstable, label="unstable")
                print(f"  imposed {imposed} of {len(unstable)}")

        print(f"\nComputing d{r}...")
        compute_to_fixpoint(ss, args.verify_converged)

        # Close still-open differentials with the in-house resolver (product
        # and map reasoning): the self-contained replacement for the
        # Spurious{r}.txt hand data. Entries it cannot derive are left
        # genuinely uncertain rather than pinned from an outside list.
        print(f"\nResolving spurious uncertainties on d{r}...")
        ss.current_page.resolve_spurious_uncertainties()

        ss.current_page.save_d(f"data/E{r}/d{r}")
        ss.write_spheres()

    print("\n" + "=" * 80)
    print("COMPUTATION COMPLETE")
    print("=" * 80)
    print("Differentials saved to data/E{r}/d{r} (proof chains) and d{r}_unknown.csv "
          "for each page r.")
    print("Charts saved to charts/")


if __name__ == "__main__":
    main()
