#!/usr/bin/env sage-python
"""
Compute Adams differentials d2 through d8 (default --stop-after 8) of the
EHP spectral sequence from the lambda algebra E2 data (with C2 map data),
and write chart CSVs (spheres plus the n=0 C2 column) for each page.

Run from this directory with:  sage -python run.py [tot] [--data DIR]

Only tridegrees with s+f <= tot and n <= 2*tot are loaded; deductions beyond
those bounds would rest on incomplete data. Outputs are written relative to
the current directory, so run from python/.

Inputs:
  --data DIR - E2 page data generated by the rust lambda algebra code
               (default: data/E2):
               E2_{rank,relations,E,H,P,C2}.csv (+ optional E2_names.json).
  stable/   - known differentials: stable_sphere_diffs.csv applies to every
              sphere in the stable range (n > s+1), c2_diffs.csv to the n=0
              column (both resolved by check_stable() during compute());
              the hand lists Contradiction3.txt (d3, proof by contradiction)
              and Spurious4.txt (d4, easy spurious) are imposed before
              compute() on E3/E4

Every page is computed fresh from the E2 data and the page turns: d2 first,
then d3 through d8 as the page turns. d2 is written once under --data (as a
plain output, never reloaded); d3-d8 are saved to data/E{r}/d{r}.

Outputs:
  <DIR>/d2                - the d2 differential (JSON), written under --data
  data/E{r}/d{r}          - differential data with proof chains (JSON), plus
                            d{r}_unknown.csv with the tridegrees where d_r
                            remains undetermined (d3-d8)
  charts/E{r}_{tot}.csv   - chart data for each page (includes the n=0 C2 column)
  data/E{r}/              - full page data for E3-E8
"""

import argparse
import os

from sage.all import GF, vector

from ehp_adams import SpectralSequence
from lib import Element

TOT = 70  # default total degree; the loader lowers it if the data covers less

def load_entry_list(path):
    """Parse a hand-written differential list into (n, s, f, row, col, value)
    tuples. Lines are `n s f row col value`; blank lines and `#` comments are
    ignored. Missing file -> empty list. Used for the optional hand lists
    Contradiction3.txt / Spurious4.txt (hand-proved differentials layered on top of the stable
    inputs; see stable/README.md for the input-data conventions)."""
    entries = []
    if not os.path.exists(path):
        return entries
    with open(path) as fh:
        for lineno, line in enumerate(fh, 1):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            # A malformed line is a hand-editing accident; silently dropping
            # it would silently delete a hand-proved differential, so fail
            # loudly instead.
            if len(parts) != 6:
                raise ValueError(
                    f"{path}:{lineno}: malformed hand-list line "
                    f"(expected 6 whitespace-separated fields): {line!r}")
            try:
                entries.append(tuple(int(x) for x in parts))
            except ValueError as exc:
                raise ValueError(
                    f"{path}:{lineno}: non-integer field in hand-list "
                    f"line: {line!r}") from exc
    return entries


def _differential_state(page):
    """Comparable snapshot of a page's derived state: the dimension of the
    differential constraint space at every populated tridegree, plus the set
    of uncertain tridegrees. compute() only narrows spaces and resolves
    uncertainties, so two equal snapshots mean a fixpoint was reached."""
    dims = {}
    for tri, dim in page.dimension.items():
        if dim > 0:
            dims[tri] = page.d[tri].dimension()
    uncertain = page.uncertainty_manager.uncertain
    uncertain_keys = (
        sorted(uncertain.keys()) if hasattr(uncertain, "keys") else len(uncertain))
    return dims, uncertain_keys


MAX_EXTRA_CONVERGENCE_PASSES = 5


def compute_to_fixpoint(ss, verify):
    """ss.compute(), optionally re-run until the differential state stops
    changing. compute() exits only when a full constraint pass changes
    nothing, so `verify` is an independent double-check of that exit test;
    0 extra passes = converged first try (the expected outcome)."""
    ss.compute()
    if not verify:
        return
    for extra in range(1, MAX_EXTRA_CONVERGENCE_PASSES + 1):
        before = _differential_state(ss.current_page)
        ss.compute()
        after = _differential_state(ss.current_page)
        if before == after:
            print(f"  convergence verified ({extra - 1} extra pass(es) needed)")
            return
        changed = sorted(
            set(k for k in after[0] if before[0].get(k) != after[0][k])
            | set(before[0]) - set(after[0]))
        print(f"  WARNING: compute() had not converged; extra pass {extra} "
              f"changed {len(changed)} tridegree(s), e.g. {changed[:8]}")
    raise RuntimeError(
        f"compute() still changing after {MAX_EXTRA_CONVERGENCE_PASSES} extra "
        f"passes; do not trust this state")


def stable_path(name):
    """Resolve a filename under the stable/ dir (run from python/), matching
    check_stable's convention."""
    return os.path.join("stable", name) if os.path.isdir("stable") else name


def main():
    parser = argparse.ArgumentParser(
        description="Compute Adams differentials d2-d8 of the EHP spectral sequence."
    )
    parser.add_argument(
        "tot", nargs="?", type=int, default=TOT,
        help=f"maximum total degree s+f to load (default: {TOT})",
    )
    parser.add_argument(
        "--data", default="data/E2", metavar="DIR",
        help="directory with the rust-generated E2 CSVs (default: data/E2)",
    )
    parser.add_argument(
        "--charts-dir", default=None, metavar="DIR",
        help="directory for the per-page chart CSVs E{r}_{tot}.csv "
             "(default: charts/). Use a separate dir to keep runs side by side.",
    )
    parser.add_argument(
        "--stop-after", type=int, default=8, metavar="R",
        help="highest page E_R to compute; pass 2 to stop right after d2 "
             "(default: 8)",
    )
    parser.add_argument(
        "--verify-converged", action="store_true",
        help="after each compute(), re-run it until the differential state "
             "stops changing and report how many extra passes were needed. "
             "Independent check of compute()'s fixpoint exit test; use "
             "for the definitive publication run (expected: 0 extra passes).",
    )
    args = parser.parse_args()
    tot = args.tot

    print("=" * 80)
    print(f"LOADING E2 PAGE FROM {args.data} (tot={tot})")
    print("=" * 80)
    # The C2 map is detected from the presence of E2_C2.csv in the data dir.
    ss = SpectralSequence.from_data(args.data, r=2, tot=tot)

    # Compute d2: check_stable fills the stable/C2 differentials, the
    # filtration-1 Leibniz (h0-h3 maps) resolves the rest of the C2 column,
    # and naturality pulls that to the odd spheres. d2 is recomputed every run
    # (never preloaded) and written once under --data as a plain output, so
    # why.py can render d2 proof diagrams.
    print("\nComputing d2...")
    compute_to_fixpoint(ss, args.verify_converged)
    ss.current_page.save_d(os.path.join(args.data, "d2"))
    ss.write_spheres(charts_dir=args.charts_dir)  # E2 chart

    for r in range(3, 9):
        if r > args.stop_after:
            break
        print("\n" + "=" * 80)
        print(f"TURNING PAGE TO E{r}")
        print("=" * 80)
        ss.next_page()  # induces maps (incl. C2), products, names; saves data/E{r}/

        # Hand-imposed differentials, applied BEFORE compute so they
        # propagate: d3 by proof by contradiction (Contradiction3.txt), d4
        # easy spurious differentials the resolver cannot yet derive
        # (Spurious4.txt).
        hand_list = {3: "Contradiction3.txt", 4: "Spurious4.txt"}.get(r)
        if hand_list:
            unstable = load_entry_list(stable_path(hand_list))
            if unstable:
                print(f"\nApplying {len(unstable)} hand d{r} "
                      f"differentials from {hand_list}...")
                imposed = ss.current_page.d.apply_entry_list(unstable, label="unstable")
                print(f"  imposed {imposed} of {len(unstable)}")

        print(f"\nComputing d{r}...")
        compute_to_fixpoint(ss, args.verify_converged)

        # Close still-open differentials with the in-house resolver (product
        # and map reasoning): the self-contained replacement for the
        # Spurious{r}.txt hand data. Entries it cannot derive are left
        # genuinely uncertain rather than pinned from an outside list.
        print(f"\nResolving spurious uncertainties on d{r}...")
        ss.current_page.resolve_spurious_uncertainties()

        ss.current_page.save_d(f"data/E{r}/d{r}")
        ss.write_spheres(charts_dir=args.charts_dir)

    print("\n" + "=" * 80)
    print("COMPUTATION COMPLETE")
    print("=" * 80)
    print("Differentials saved to data/E{r}/d{r} (proof chains) and d{r}_unknown.csv "
          "for each page r.")
    print("Charts saved to charts/")


if __name__ == "__main__":
    main()
